namespace :schedule do
  desc "Import Schedule Master from hardcoded data"
  task import_master: :environment do
    template_id = 34

    # Clear existing rows first
    deleted = ScheduleTemplateRow.where(schedule_template_id: template_id).delete_all
    puts "Deleted #{deleted} existing rows"

    data = [
      { "name"=>"CREATE - Contract", "predecessor_ids"=>[], "duration"=>1, "sequence_order"=>1 },
      { "name"=>"DO - Load Invoices into XERO", "predecessor_ids"=>[ { "id"=>1, "type"=>"FS", "lag"=>0 } ], "duration"=>1, "sequence_order"=>2 },
      { "name"=>"GET - Finance Approval", "predecessor_ids"=>[ { "id"=>1, "type"=>"FS", "lag"=>0 } ], "duration"=>21, "sequence_order"=>3 },
      { "name"=>"CLAIM - DEPOSIT", "predecessor_ids"=>[ { "id"=>3, "type"=>"FS", "lag"=>0 } ], "duration"=>5, "sequence_order"=>4 },
      { "name"=>"ORDER - Soil Test and Wind Rating & Slab Design", "predecessor_ids"=>[ { "id"=>4, "type"=>"FS", "lag"=>0 } ], "duration"=>5, "sequence_order"=>5 },
      { "name"=>"ORDER - Contour Survey Plan", "predecessor_ids"=>[ { "id"=>4, "type"=>"FS", "lag"=>0 } ], "duration"=>5, "sequence_order"=>6 },
      { "name"=>"DO - Working Drawings", "predecessor_ids"=>[ { "id"=>4, "type"=>"FS", "lag"=>0 }, { "id"=>6, "type"=>"FS", "lag"=>0 } ], "duration"=>1, "sequence_order"=>7 },
      { "name"=>"DO - Plumbing Approval", "predecessor_ids"=>[ { "id"=>3, "type"=>"FS", "lag"=>0 }, { "id"=>4, "type"=>"FS", "lag"=>0 } ], "duration"=>1, "sequence_order"=>8 },
      { "name"=>"DO - QLeave", "predecessor_ids"=>[ { "id"=>3, "type"=>"FS", "lag"=>0 }, { "id"=>4, "type"=>"FS", "lag"=>0 } ], "duration"=>1, "sequence_order"=>9 },
      { "name"=>"DO - Hydraulics Design", "predecessor_ids"=>[ { "id"=>3, "type"=>"FS", "lag"=>0 }, { "id"=>4, "type"=>"FS", "lag"=>0 } ], "duration"=>1, "sequence_order"=>10 },
      { "name"=>"DO - Energy Efficiency", "predecessor_ids"=>[ { "id"=>3, "type"=>"FS", "lag"=>0 }, { "id"=>4, "type"=>"FS", "lag"=>0 } ], "duration"=>1, "sequence_order"=>11 },
      { "name"=>"CHECK - Land Settlement", "predecessor_ids"=>[ { "id"=>3, "type"=>"FS", "lag"=>0 }, { "id"=>4, "type"=>"FS", "lag"=>0 } ], "duration"=>1, "sequence_order"=>12 },
      { "name"=>"DO - Covenant Approval (if required)", "predecessor_ids"=>[ { "id"=>7, "type"=>"FS", "lag"=>0 } ], "duration"=>1, "sequence_order"=>13 },
      { "name"=>"DO - Certification", "predecessor_ids"=>[ { "id"=>8, "type"=>"FS", "lag"=>0 }, { "id"=>9, "type"=>"FS", "lag"=>0 }, { "id"=>10, "type"=>"FS", "lag"=>0 }, { "id"=>11, "type"=>"FS", "lag"=>0 } ], "duration"=>10, "sequence_order"=>14 },
      { "name"=>"DO - Driveway Application", "predecessor_ids"=>[ { "id"=>14, "type"=>"FS", "lag"=>0 } ], "duration"=>1, "sequence_order"=>15 },
      { "name"=>"Req Site Cut", "predecessor_ids"=>[ { "id"=>12, "type"=>"FS", "lag"=>0 }, { "id"=>14, "type"=>"FS", "lag"=>0 } ], "duration"=>1, "sequence_order"=>16 },
      { "name"=>"SLAB", "predecessor_ids"=>[], "duration"=>16, "sequence_order"=>17 },
      { "name"=>"Req Surveyor to Setout Wafflepod", "predecessor_ids"=>[ { "id"=>26, "type"=>"FS", "lag"=>0 } ], "duration"=>1, "sequence_order"=>18 },
      { "name"=>"Req Drainer for Drains Wafflepod", "predecessor_ids"=>[ { "id"=>28, "type"=>"FS", "lag"=>0 } ], "duration"=>2, "sequence_order"=>19 },
      { "name"=>"Req Electrician Underground (INC NBN)", "predecessor_ids"=>[], "duration"=>1, "sequence_order"=>20 },
      { "name"=>"Req Power To Site", "predecessor_ids"=>[ { "id"=>30, "type"=>"FS", "lag"=>0 } ], "duration"=>10, "sequence_order"=>21 },
      { "name"=>"Req Concreter For Complete Slab Labour And Materials", "predecessor_ids"=>[ { "id"=>28, "type"=>"FS", "lag"=>0 }, { "id"=>29, "type"=>"FS", "lag"=>0 }, { "id"=>30, "type"=>"FS", "lag"=>0 } ], "duration"=>2, "sequence_order"=>22 },
      { "name"=>"Req Termite Protection Penetrations", "predecessor_ids"=>[], "duration"=>1, "sequence_order"=>23 },
      { "name"=>"PHOTO - Slab", "predecessor_ids"=>[ { "id"=>32, "type"=>"FS", "lag"=>0 } ], "duration"=>1, "sequence_order"=>24 },
      { "name"=>"Req Waterproof Slab Edge", "predecessor_ids"=>[ { "id"=>32, "type"=>"FS", "lag"=>0 } ], "duration"=>1, "sequence_order"=>25 },
      { "name"=>"CLAIM - Slab", "predecessor_ids"=>[ { "id"=>32, "type"=>"FS", "lag"=>0 } ], "duration"=>5, "sequence_order"=>26 },
      { "name"=>"CERTIFICATE - Surveyor", "predecessor_ids"=>[], "duration"=>1, "sequence_order"=>27 },
      { "name"=>"CERTIFICATE - Engineer Slab", "predecessor_ids"=>[], "duration"=>1, "sequence_order"=>28 },
      { "name"=>"FRAME", "predecessor_ids"=>[], "duration"=>12, "sequence_order"=>29 },
      { "name"=>"Req Frame Hardware", "predecessor_ids"=>[], "duration"=>1, "sequence_order"=>30 },
      { "name"=>"Req Frame Material Ground Floor", "predecessor_ids"=>[], "duration"=>1, "sequence_order"=>31 },
      { "name"=>"Req Carpenter Ground Floor", "predecessor_ids"=>[], "duration"=>5, "sequence_order"=>32 },
      { "name"=>"Req Termite Perimeter", "predecessor_ids"=>[], "duration"=>1, "sequence_order"=>33 },
      { "name"=>"Req Roof Trusses", "predecessor_ids"=>[], "duration"=>1, "sequence_order"=>34 },
      { "name"=>"Req Crane Roof Trusses", "predecessor_ids"=>[], "duration"=>1, "sequence_order"=>35 },
      { "name"=>"Req Steel Posts", "predecessor_ids"=>[ { "id"=>44, "type"=>"FS", "lag"=>0 } ], "duration"=>1, "sequence_order"=>36 },
      { "name"=>"PHOTO - Frame", "predecessor_ids"=>[ { "id"=>42, "type"=>"FS", "lag"=>0 } ], "duration"=>1, "sequence_order"=>37 },
      { "name"=>"Do Frame Inspection", "predecessor_ids"=>[ { "id"=>42, "type"=>"FS", "lag"=>0 } ], "duration"=>1, "sequence_order"=>38 },
      { "name"=>"Req Partition Wall", "predecessor_ids"=>[ { "id"=>42, "type"=>"FS", "lag"=>0 } ], "duration"=>1, "sequence_order"=>39 },
      { "name"=>"CERTIFICATE - Engineer Frame INC Hoist", "predecessor_ids"=>[ { "id"=>48, "type"=>"FS", "lag"=>0 } ], "duration"=>1, "sequence_order"=>40 },
      { "name"=>"CERTIFICATE - Termite", "predecessor_ids"=>[], "duration"=>1, "sequence_order"=>41 },
      { "name"=>"CLAIM - Frame", "predecessor_ids"=>[ { "id"=>42, "type"=>"FS", "lag"=>0 }, { "id"=>47, "type"=>"FS", "lag"=>0 } ], "duration"=>5, "sequence_order"=>42 },
      { "name"=>"CERTIFICATE - Roof Trusses", "predecessor_ids"=>[], "duration"=>1, "sequence_order"=>43 },
      { "name"=>"ENCLOSED", "predecessor_ids"=>[], "duration"=>19, "sequence_order"=>44 },
      { "name"=>"Req Fascia and Gutter and Colorbond Roof", "predecessor_ids"=>[ { "id"=>42, "type"=>"FS", "lag"=>0 }, { "id"=>49, "type"=>"FS", "lag"=>0 } ], "duration"=>5, "sequence_order"=>45 },
      { "name"=>"Req External Doors", "predecessor_ids"=>[], "duration"=>1, "sequence_order"=>46 },
      { "name"=>"Req Windows", "predecessor_ids"=>[], "duration"=>1, "sequence_order"=>47 },
      { "name"=>"Req External Door Handle Locks", "predecessor_ids"=>[], "duration"=>1, "sequence_order"=>48 },
      { "name"=>"Req Carpenter Install Windows/Doors", "predecessor_ids"=>[ { "id"=>42, "type"=>"FS", "lag"=>0 }, { "id"=>49, "type"=>"FS", "lag"=>0 }, { "id"=>57, "type"=>"FS", "lag"=>0 } ], "duration"=>1, "sequence_order"=>49 },
      { "name"=>"Req Carpenter Straighten Frame", "predecessor_ids"=>[], "duration"=>1, "sequence_order"=>50 },
      { "name"=>"Req Mixer Bodies For Plumber Rough In", "predecessor_ids"=>[], "duration"=>1, "sequence_order"=>51 },
      { "name"=>"FIT - Window Actuators", "predecessor_ids"=>[ { "id"=>57, "type"=>"FS", "lag"=>0 } ], "duration"=>1, "sequence_order"=>52 },
      { "name"=>"Req Wall Sisilation Ground Floor", "predecessor_ids"=>[], "duration"=>1, "sequence_order"=>53 },
      { "name"=>"Req Measure Garage Doors", "predecessor_ids"=>[ { "id"=>59, "type"=>"FS", "lag"=>0 } ], "duration"=>1, "sequence_order"=>54 },
      { "name"=>"Req Rough In Solar Panels", "predecessor_ids"=>[ { "id"=>55, "type"=>"FS", "lag"=>0 } ], "duration"=>1, "sequence_order"=>55 },
      { "name"=>"Req Air Conditioning Rough In", "predecessor_ids"=>[ { "id"=>55, "type"=>"FS", "lag"=>0 } ], "duration"=>1, "sequence_order"=>56 },
      { "name"=>"Req Electrician - Prewire", "predecessor_ids"=>[ { "id"=>55, "type"=>"FS", "lag"=>0 } ], "duration"=>3, "sequence_order"=>57 },
      { "name"=>"Req Plumber Rough In", "predecessor_ids"=>[ { "id"=>55, "type"=>"FS", "lag"=>0 } ], "duration"=>3, "sequence_order"=>58 },
      { "name"=>"Req Soffit Hardware and Cladding", "predecessor_ids"=>[ { "id"=>55, "type"=>"FS", "lag"=>0 } ], "duration"=>1, "sequence_order"=>59 },
      { "name"=>"Req Fire Rough In", "predecessor_ids"=>[ { "id"=>55, "type"=>"FS", "lag"=>0 } ], "duration"=>1, "sequence_order"=>60 },
      { "name"=>"Req Carpenter Soffits Ground Floor", "predecessor_ids"=>[ { "id"=>55, "type"=>"FS", "lag"=>0 }, { "id"=>69, "type"=>"FS", "lag"=>0 } ], "duration"=>2, "sequence_order"=>61 },
      { "name"=>"Req Install Ply to Bathrooms", "predecessor_ids"=>[ { "id"=>68, "type"=>"FS", "lag"=>0 } ], "duration"=>1, "sequence_order"=>62 },
      { "name"=>"Do Plumbing Rough-In Inspection", "predecessor_ids"=>[ { "id"=>68, "type"=>"FS", "lag"=>0 } ], "duration"=>1, "sequence_order"=>63 },
      { "name"=>"Req Carpenter Cladding", "predecessor_ids"=>[ { "id"=>71, "type"=>"FS", "lag"=>0 } ], "duration"=>5, "sequence_order"=>64 },
      { "name"=>"Do Inspection NDIS", "predecessor_ids"=>[ { "id"=>72, "type"=>"FS", "lag"=>0 } ], "duration"=>1, "sequence_order"=>65 },
      { "name"=>"PHOTO - Ply Bathrooms, Bedroom Crane Supports", "predecessor_ids"=>[ { "id"=>72, "type"=>"FS", "lag"=>0 } ], "duration"=>1, "sequence_order"=>66 },
      { "name"=>"CERTIFICATE - Windows", "predecessor_ids"=>[], "duration"=>1, "sequence_order"=>67 },
      { "name"=>"PHOTO - Enclosed", "predecessor_ids"=>[ { "id"=>74, "type"=>"FS", "lag"=>0 } ], "duration"=>1, "sequence_order"=>68 },
      { "name"=>"Req Down Pipes Ground Floor", "predecessor_ids"=>[ { "id"=>74, "type"=>"FS", "lag"=>0 } ], "duration"=>1, "sequence_order"=>69 },
      { "name"=>"CLAIM - Enclosed", "predecessor_ids"=>[ { "id"=>74, "type"=>"FS", "lag"=>0 }, { "id"=>78, "type"=>"FS", "lag"=>0 } ], "duration"=>5, "sequence_order"=>70 },
      { "name"=>"FIXING", "predecessor_ids"=>[], "duration"=>35, "sequence_order"=>71 },
      { "name"=>"Req Ceiling & Wall Insulation Before Plasterboard", "predecessor_ids"=>[ { "id"=>68, "type"=>"FS", "lag"=>0 }, { "id"=>67, "type"=>"FS", "lag"=>0 }, { "id"=>70, "type"=>"FS", "lag"=>0 }, { "id"=>66, "type"=>"FS", "lag"=>0 }, { "id"=>65, "type"=>"FS", "lag"=>0 } ], "duration"=>1, "sequence_order"=>72 },
      { "name"=>"Req Plaster Board", "predecessor_ids"=>[ { "id"=>73, "type"=>"FS", "lag"=>0 }, { "id"=>66, "type"=>"FS", "lag"=>0 }, { "id"=>67, "type"=>"FS", "lag"=>0 }, { "id"=>68, "type"=>"FS", "lag"=>0 }, { "id"=>82, "type"=>"FS", "lag"=>0 } ], "duration"=>7, "sequence_order"=>73 },
      { "name"=>"Req Internal Fixout", "predecessor_ids"=>[], "duration"=>1, "sequence_order"=>74 },
      { "name"=>"Req Carpenter Fixout", "predecessor_ids"=>[ { "id"=>83, "type"=>"FS", "lag"=>0 } ], "duration"=>2, "sequence_order"=>75 },
      { "name"=>"Req Garage Doors", "predecessor_ids"=>[ { "id"=>83, "type"=>"FS", "lag"=>0 } ], "duration"=>1, "sequence_order"=>76 },
      { "name"=>"SPO - Electrician - Cutouts", "predecessor_ids"=>[ { "id"=>83, "type"=>"FS", "lag"=>0 } ], "duration"=>1, "sequence_order"=>77 },
      { "name"=>"Req Internal Door Handles", "predecessor_ids"=>[], "duration"=>1, "sequence_order"=>78 },
      { "name"=>"FIT - Auto Door Openers", "predecessor_ids"=>[ { "id"=>85, "type"=>"FS", "lag"=>0 } ], "duration"=>2, "sequence_order"=>79 },
      { "name"=>"Req Kitchen", "predecessor_ids"=>[ { "id"=>85, "type"=>"FS", "lag"=>0 } ], "duration"=>5, "sequence_order"=>80 },
      { "name"=>"Req Water Proofer", "predecessor_ids"=>[ { "id"=>85, "type"=>"FS", "lag"=>0 } ], "duration"=>2, "sequence_order"=>81 },
      { "name"=>"Req Tiles", "predecessor_ids"=>[], "duration"=>1, "sequence_order"=>82 },
      { "name"=>"Req Tiler", "predecessor_ids"=>[ { "id"=>90, "type"=>"FS", "lag"=>0 }, { "id"=>91, "type"=>"FS", "lag"=>0 } ], "duration"=>7, "sequence_order"=>83 },
      { "name"=>"SPO - Plaster Fit Cornice", "predecessor_ids"=>[ { "id"=>90, "type"=>"FS", "lag"=>0 } ], "duration"=>1, "sequence_order"=>84 },
      { "name"=>"CERTIFICATE - Waterproofer", "predecessor_ids"=>[], "duration"=>1, "sequence_order"=>85 },
      { "name"=>"Req Painter Internal  House", "predecessor_ids"=>[ { "id"=>93, "type"=>"FS", "lag"=>0 } ], "duration"=>7, "sequence_order"=>86 },
      { "name"=>"Measure Shower Screens Book Fitting", "predecessor_ids"=>[ { "id"=>93, "type"=>"FS", "lag"=>0 } ], "duration"=>1, "sequence_order"=>87 },
      { "name"=>"Req Pre Paint (Including Sanding)", "predecessor_ids"=>[], "duration"=>2, "sequence_order"=>88 },
      { "name"=>"PHOTO - Fixing", "predecessor_ids"=>[ { "id"=>92, "type"=>"FS", "lag"=>0 }, { "id"=>96, "type"=>"FS", "lag"=>0 } ], "duration"=>1, "sequence_order"=>89 },
      { "name"=>"Req Painter External House", "predecessor_ids"=>[ { "id"=>96, "type"=>"FS", "lag"=>0 }, { "id"=>74, "type"=>"FS", "lag"=>0 }, { "id"=>79, "type"=>"FS", "lag"=>0 } ], "duration"=>2, "sequence_order"=>90 },
      { "name"=>"CLAIM - Fixing", "predecessor_ids"=>[ { "id"=>93, "type"=>"FS", "lag"=>0 }, { "id"=>96, "type"=>"FS", "lag"=>0 }, { "id"=>99, "type"=>"FS", "lag"=>0 } ], "duration"=>5, "sequence_order"=>91 },
      { "name"=>"DRIVEWAY", "predecessor_ids"=>[], "duration"=>4, "sequence_order"=>92 },
      { "name"=>"Req Driveway Kerb Cut Out", "predecessor_ids"=>[], "duration"=>1, "sequence_order"=>93 },
      { "name"=>"FIT - Drains to Front of Doors", "predecessor_ids"=>[], "duration"=>1, "sequence_order"=>94 },
      { "name"=>"Req Driveway Steel Reo", "predecessor_ids"=>[], "duration"=>1, "sequence_order"=>95 },
      { "name"=>"Req Driveway Concretor", "predecessor_ids"=>[ { "id"=>79, "type"=>"FS", "lag"=>0 }, { "id"=>93, "type"=>"FS", "lag"=>0 } ], "duration"=>1, "sequence_order"=>96 },
      { "name"=>"PHOTO - Driveway", "predecessor_ids"=>[ { "id"=>106, "type"=>"FS", "lag"=>0 } ], "duration"=>1, "sequence_order"=>97 },
      { "name"=>"LANDSCAPING", "predecessor_ids"=>[], "duration"=>8, "sequence_order"=>98 },
      { "name"=>"Req Retaining Wall", "predecessor_ids"=>[ { "id"=>106, "type"=>"FS", "lag"=>0 } ], "duration"=>2, "sequence_order"=>99 },
      { "name"=>"Req Fence", "predecessor_ids"=>[ { "id"=>109, "type"=>"FS", "lag"=>0 }, { "id"=>106, "type"=>"FS", "lag"=>0 } ], "duration"=>2, "sequence_order"=>100 },
      { "name"=>"Req Landscaping", "predecessor_ids"=>[ { "id"=>110, "type"=>"FS", "lag"=>0 } ], "duration"=>3, "sequence_order"=>101 },
      { "name"=>"PHOTO - Fence and Landscaping", "predecessor_ids"=>[ { "id"=>110, "type"=>"FS", "lag"=>0 }, { "id"=>111, "type"=>"FS", "lag"=>0 } ], "duration"=>1, "sequence_order"=>102 },
      { "name"=>"PRACTICAL COMPLETION", "predecessor_ids"=>[], "duration"=>15, "sequence_order"=>103 },
      { "name"=>"Req Hot Water System", "predecessor_ids"=>[], "duration"=>1, "sequence_order"=>104 },
      { "name"=>"Req Plumber Fitoff Gear", "predecessor_ids"=>[], "duration"=>1, "sequence_order"=>105 },
      { "name"=>"Req Fire System Fitoff", "predecessor_ids"=>[ { "id"=>96, "type"=>"FS", "lag"=>0 }, { "id"=>93, "type"=>"FS", "lag"=>0 } ], "duration"=>1, "sequence_order"=>106 },
      { "name"=>"Req Electrical Items", "predecessor_ids"=>[], "duration"=>1, "sequence_order"=>107 },
      { "name"=>"Req Vinyl Sliders", "predecessor_ids"=>[ { "id"=>96, "type"=>"FS", "lag"=>0 }, { "id"=>93, "type"=>"FS", "lag"=>0 } ], "duration"=>1, "sequence_order"=>108 },
      { "name"=>"Req Window Coverings", "predecessor_ids"=>[ { "id"=>96, "type"=>"FS", "lag"=>0 }, { "id"=>93, "type"=>"FS", "lag"=>0 } ], "duration"=>1, "sequence_order"=>109 },
      { "name"=>"Req Carpenter For Final Fitoff", "predecessor_ids"=>[ { "id"=>93, "type"=>"FS", "lag"=>0 }, { "id"=>96, "type"=>"FS", "lag"=>0 } ], "duration"=>1, "sequence_order"=>110 },
      { "name"=>"Req Plumber - Fit Off", "predecessor_ids"=>[ { "id"=>93, "type"=>"FS", "lag"=>0 }, { "id"=>96, "type"=>"FS", "lag"=>0 } ], "duration"=>2, "sequence_order"=>111 },
      { "name"=>"Req Shower Screens", "predecessor_ids"=>[ { "id"=>93, "type"=>"FS", "lag"=>0 }, { "id"=>96, "type"=>"FS", "lag"=>0 } ], "duration"=>1, "sequence_order"=>112 },
      { "name"=>"Req SAT System", "predecessor_ids"=>[], "duration"=>1, "sequence_order"=>113 },
      { "name"=>"CERTIFICATE - Fire Alarms", "predecessor_ids"=>[ { "id"=>116, "type"=>"FS", "lag"=>0 } ], "duration"=>1, "sequence_order"=>114 },
      { "name"=>"CERTIFICATE - Shower Screens", "predecessor_ids"=>[ { "id"=>122, "type"=>"FS", "lag"=>0 } ], "duration"=>1, "sequence_order"=>115 },
      { "name"=>"Do Finishing Touches", "predecessor_ids"=>[ { "id"=>120, "type"=>"FS", "lag"=>0 } ], "duration"=>5, "sequence_order"=>116 },
      { "name"=>"Req Electrician - Fit Off", "predecessor_ids"=>[ { "id"=>93, "type"=>"FS", "lag"=>0 }, { "id"=>96, "type"=>"FS", "lag"=>0 }, { "id"=>119, "type"=>"FS", "lag"=>0 } ], "duration"=>3, "sequence_order"=>117 },
      { "name"=>"Do Plumbing Final Inspection", "predecessor_ids"=>[ { "id"=>121, "type"=>"FS", "lag"=>0 } ], "duration"=>1, "sequence_order"=>118 },
      { "name"=>"Req Gapping To Skirting and Expansion Joints", "predecessor_ids"=>[ { "id"=>121, "type"=>"FS", "lag"=>0 }, { "id"=>120, "type"=>"FS", "lag"=>0 } ], "duration"=>1, "sequence_order"=>119 },
      { "name"=>"Req Air Conditioning Fit Off", "predecessor_ids"=>[], "duration"=>1, "sequence_order"=>120 },
      { "name"=>"GET - All Forms for Final Inspection", "predecessor_ids"=>[], "duration"=>1, "sequence_order"=>121 },
      { "name"=>"DO - Get Hot Water Rebate", "predecessor_ids"=>[ { "id"=>128, "type"=>"FS", "lag"=>0 } ], "duration"=>1, "sequence_order"=>122 },
      { "name"=>"Req Full Turn Key Package", "predecessor_ids"=>[ { "id"=>127, "type"=>"FS", "lag"=>0 }, { "id"=>121, "type"=>"FS", "lag"=>0 } ], "duration"=>1, "sequence_order"=>123 },
      { "name"=>"Req Painter Touch Ups", "predecessor_ids"=>[ { "id"=>121, "type"=>"FS", "lag"=>0 }, { "id"=>127, "type"=>"FS", "lag"=>0 }, { "id"=>118, "type"=>"FS", "lag"=>0 } ], "duration"=>1, "sequence_order"=>124 },
      { "name"=>"Req Solar Panel Commisions", "predecessor_ids"=>[ { "id"=>127, "type"=>"FS", "lag"=>0 } ], "duration"=>1, "sequence_order"=>125 },
      { "name"=>"CERTIFICATE - Electrician", "predecessor_ids"=>[ { "id"=>127, "type"=>"FS", "lag"=>0 } ], "duration"=>1, "sequence_order"=>126 },
      { "name"=>"Req Ceiling Insulation", "predecessor_ids"=>[ { "id"=>127, "type"=>"FS", "lag"=>0 }, { "id"=>135, "type"=>"FS", "lag"=>0 } ], "duration"=>1, "sequence_order"=>127 },
      { "name"=>"Req Vinyl Floor", "predecessor_ids"=>[ { "id"=>133, "type"=>"FS", "lag"=>0 } ], "duration"=>1, "sequence_order"=>128 },
      { "name"=>"Req Window Handover Service", "predecessor_ids"=>[ { "id"=>133, "type"=>"FS", "lag"=>0 } ], "duration"=>1, "sequence_order"=>129 },
      { "name"=>"SPO -  Insulation Spread Ceiling Insulation", "predecessor_ids"=>[ { "id"=>127, "type"=>"FS", "lag"=>0 }, { "id"=>135, "type"=>"FS", "lag"=>0 } ], "duration"=>1, "sequence_order"=>130 },
      { "name"=>"Do - Put Termite Sticker In MeterBox and Kitchen Cupboard", "predecessor_ids"=>[], "duration"=>1, "sequence_order"=>131 },
      { "name"=>"Req Builders Clean", "predecessor_ids"=>[ { "id"=>127, "type"=>"FS", "lag"=>0 }, { "id"=>135, "type"=>"FS", "lag"=>0 }, { "id"=>138, "type"=>"FS", "lag"=>0 }, { "id"=>126, "type"=>"FS", "lag"=>0 } ], "duration"=>1, "sequence_order"=>132 },
      { "name"=>"CERTIFICATE - Ceiling Insulation", "predecessor_ids"=>[ { "id"=>137, "type"=>"FS", "lag"=>0 } ], "duration"=>1, "sequence_order"=>133 },
      { "name"=>"PHOTO - Practical Completion", "predecessor_ids"=>[ { "id"=>142, "type"=>"FS", "lag"=>0 } ], "duration"=>1, "sequence_order"=>134 },
      { "name"=>"Do Council Final Inspection", "predecessor_ids"=>[ { "id"=>142, "type"=>"FS", "lag"=>0 } ], "duration"=>1, "sequence_order"=>135 },
      { "name"=>"GET - Form 11/21 from Certifier", "predecessor_ids"=>[ { "id"=>145, "type"=>"FS", "lag"=>0 } ], "duration"=>1, "sequence_order"=>136 },
      { "name"=>"CREATE - Builder Confirmation", "predecessor_ids"=>[ { "id"=>145, "type"=>"FS", "lag"=>0 } ], "duration"=>1, "sequence_order"=>137 },
      { "name"=>"GET - Engineer For Future Ceiling", "predecessor_ids"=>[ { "id"=>145, "type"=>"FS", "lag"=>0 } ], "duration"=>1, "sequence_order"=>138 },
      { "name"=>"GET - SDA Site Density Report", "predecessor_ids"=>[ { "id"=>145, "type"=>"FS", "lag"=>0 } ], "duration"=>1, "sequence_order"=>139 },
      { "name"=>"CREATE - Evacuation Plan", "predecessor_ids"=>[ { "id"=>145, "type"=>"FS", "lag"=>0 } ], "duration"=>1, "sequence_order"=>140 },
      { "name"=>"CLAIM - Practical Completion", "predecessor_ids"=>[ { "id"=>145, "type"=>"FS", "lag"=>0 } ], "duration"=>5, "sequence_order"=>141 },
      { "name"=>"DO - NDIS Final Inspection", "predecessor_ids"=>[ { "id"=>145, "type"=>"FS", "lag"=>0 }, { "id"=>147, "type"=>"FS", "lag"=>0 }, { "id"=>150, "type"=>"FS", "lag"=>0 } ], "duration"=>1, "sequence_order"=>142 },
      { "name"=>"DO - Final Payment has been made, Organize Handover house", "predecessor_ids"=>[ { "id"=>145, "type"=>"FS", "lag"=>0 }, { "id"=>151, "type"=>"FS", "lag"=>0 } ], "duration"=>1, "sequence_order"=>143 }
    ]

    puts "Importing #{data.length} rows to template #{template_id}..."

    data.each do |row|
      ScheduleTemplateRow.create!(
        schedule_template_id: template_id,
        name: row["name"],
        predecessor_ids: row["predecessor_ids"],
        duration: row["duration"],
        sequence_order: row["sequence_order"]
      )
    end

    puts "Done! Imported #{data.length} rows."
  end
end
